spring.application.name=geosentinel

server.servlet.context-path=/api/v1

cors.allowed-origins=http://localhost:5173,http://10.245.25.235:5173

#server.address=10.226.9.235

server.port==${PORT:8080}
spring.datasource.url=jdbc:postgresql://localhost:5432/geoguardb
spring.datasource.username=postgres
spring.datasource.password=database

spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=${JWT_SECRET_KEY}