spring.application.name=geosentinel

server.servlet.context-path=/api/v1

cors.allowed-origins=http://localhost:5173,http://10.245.25.235:5173

#server.address=10.226.9.235
#server.address=0.0.0.0
server.port=${PORT:8080}


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=${JWT_SECRET_KEY}